/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import paint.controller.PaintControl;
import paint.model.Circle;
import paint.model.Line;
import paint.model.Oval;
import paint.model.Rectangle;
import paint.model.Shape;
import paint.model.Square;
import paint.model.Triangle;
import static paint.view.MyCanvas.shapesList;

/**
 *
 * @author user
 */
public class View extends javax.swing.JFrame {

    private PaintControl controller;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jPanel2 = new MyCanvas();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Line");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(650, 290, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 20, 430, 470);

        jButton1.setFont(new java.awt.Font("Chalkboard SE", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("SQUARE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 230, 160, 60);

        jButton2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton2.setText("Change Color");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 130, 171, 29);

        jComboBox1.setFont(new java.awt.Font("Apple Chancery", 3, 24)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(21, 37, 160, 41);

        jButton3.setFont(new java.awt.Font("Chalkboard SE", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 153));
        jButton3.setText("Circle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 90, 110, 80);

        jButton4.setFont(new java.awt.Font("Chalkboard SE", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 153));
        jButton4.setText("TRIANGLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(630, 390, 180, 70);

        jButton5.setFont(new java.awt.Font("Chalkboard SE", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 153));
        jButton5.setText("RECTANGLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(630, 330, 180, 60);

        jButton6.setFont(new java.awt.Font("Chalkboard SE", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 153));
        jButton6.setText("Elipse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(640, 170, 160, 60);

        jButton7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton7.setText("Redo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(90, 250, 91, 29);

        jButton9.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton9.setText("Undo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 250, 94, 29);

        jRadioButton1.setFont(new java.awt.Font("Phosphate", 3, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 51, 255));
        jRadioButton1.setText("Select all");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 80, 170, 36);

        jButton11.setFont(new java.awt.Font("Phosphate", 3, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 51, 255));
        jButton11.setText("up");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(50, 290, 75, 31);

        jButton13.setFont(new java.awt.Font("Phosphate", 3, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 51, 255));
        jButton13.setText("left ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(0, 320, 80, 31);

        jButton14.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton14.setText("Edit");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(50, 160, 84, 29);

        jButton15.setFont(new java.awt.Font("Phosphate", 3, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 51, 255));
        jButton15.setText("right");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(80, 320, 91, 31);

        jButton12.setFont(new java.awt.Font("Phosphate", 3, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 51, 255));
        jButton12.setText("down");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(40, 350, 95, 31);

        jButton10.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 0, 153));
        jButton10.setText("LINE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(650, 300, 150, 20);

        jButton16.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton16.setText("Remove");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(30, 190, 130, 30);

        jButton17.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton17.setText("save");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(10, 380, 86, 29);

        jButton18.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton18.setText("Load");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(90, 380, 90, 29);

        jButton19.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton19.setText("copy");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(50, 220, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int result;
        int i = jComboBox1.getSelectedIndex();
        try {
            MyCanvas c = (MyCanvas) jPanel2;
            JPanel panel = new JPanel();
            JColorChooser colorChooser = new JColorChooser(c.shapesList.get(i).getColor());
            panel.add(colorChooser);
            result = JOptionPane.showConfirmDialog(null, panel, "Choose Color", JOptionPane.OK_CANCEL_OPTION);
            if (jRadioButton1.isSelected() == true) {
                for (Shape s : shapesList) {
                    s.setColor(colorChooser.getColor());
                }
            } else {
                c.shapesList.get(i).setColor(colorChooser.getColor());
            }

            c.repaint();

        } catch (Exception E) {
            System.out.println(E);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        // jComboBox1.setRenderer(new MyComboBoxRenderer("SHAPES"));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Circle cir = new Circle(50);
        if (cir.result == JOptionPane.OK_OPTION) {
            controller.addShape(cir);

        }
        this.jComboBox1.addItem("circle" + counter++);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Square r = new Square(50);
        if (r.result == JOptionPane.OK_OPTION) {
            controller.addShape(r);

        }
        this.jComboBox1.addItem("square" + counter++);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Rectangle r = new Rectangle(50);
        MyCanvas c = (MyCanvas) jPanel2;
        if (r.result == JOptionPane.OK_OPTION) {
            controller.addShape(r);
            this.jComboBox1.addItem("Rectangle" + counter++);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4 = new TriangleButton();
        Triangle r = new Triangle(50);
        MyCanvas c = (MyCanvas) jPanel2;
        if (r.result == JOptionPane.OK_OPTION) {
            controller.addShape(r);
            this.jComboBox1.addItem("Triangle" + counter++);

    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        controller.undo();   //TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        controller.redo();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Oval ov = new Oval(50);
        //  jButton6 = new RoundButton();
        if (ov.result == JOptionPane.OK_OPTION) {
            controller.addShape(ov);

        }
        this.jComboBox1.addItem("oval" + counter++);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Line l = new Line(50);
        if (l.result == JOptionPane.OK_OPTION) {
            controller.addShape(l);

        }
        this.jComboBox1.addItem("line" + counter++);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int i = jComboBox1.getSelectedIndex();

        try {
            MyCanvas c = (MyCanvas) jPanel2;
            Shape s = (Shape) c.shapesList.get(i).getClass().newInstance();
            Color c1 = (Color) c.shapesList.get(i).getColor();
            s.setPosition(c.shapesList.get(i).getPosition());

            c.shapesList.remove(i);
            c.shapesList.add(i, s);
            c.shapesList.get(i).setColor(c1);
            c.repaint();
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int i = jComboBox1.getSelectedIndex();
        MyCanvas c = (MyCanvas) jPanel2;

        if (jRadioButton1.isSelected() == true) {
            for (Shape s : shapesList) {
                Point position = s.getPosition();
                s.setPosition(new Point((int) position.getX(), (int) position.getY() - 10));
            }
        } else {
            Point position = c.shapesList.get(i).getPosition();
            c.shapesList.get(i).setPosition(new Point((int) position.getX(), (int) position.getY() - 10));
        }
        c.repaint();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int i = jComboBox1.getSelectedIndex();
        MyCanvas c = (MyCanvas) jPanel2;

        if (jRadioButton1.isSelected() == true) {
            for (Shape s : shapesList) {
                Point position = s.getPosition();
                s.setPosition(new Point((int) position.getX(), (int) position.getY() + 10));
            }
        } else {
            Point position = c.shapesList.get(i).getPosition();
            c.shapesList.get(i).setPosition(new Point((int) position.getX(), (int) position.getY() + 10));
        }
        c.repaint();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int i = jComboBox1.getSelectedIndex();
        MyCanvas c = (MyCanvas) jPanel2;
        if (jRadioButton1.isSelected() == true) {
            for (Shape s : shapesList) {
                Point position = s.getPosition();
                s.setPosition(new Point((int) position.getX() - 10, (int) position.getY()));
            }
        } else {
            Point position = c.shapesList.get(i).getPosition();
            c.shapesList.get(i).setPosition(new Point((int) position.getX() - 10, (int) position.getY()));
        }
        c.repaint();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        int i = jComboBox1.getSelectedIndex();
        MyCanvas c = (MyCanvas) jPanel2;
        if (jRadioButton1.isSelected() == true) {
            for (Shape s : shapesList) {
                Point position = s.getPosition();
                s.setPosition(new Point((int) position.getX() + 10, (int) position.getY()));
            }
        } else {
            Point position = c.shapesList.get(i).getPosition();
            c.shapesList.get(i).setPosition(new Point((int) position.getX() + 10, (int) position.getY()));
        }
        c.repaint();


    }//GEN-LAST:event_jButton15ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.out.println("trials");
        Line l = new Line(50);
        System.out.println("2");
        if (l.result == JOptionPane.OK_OPTION) {
            controller.addShape(l);

        }
        this.jComboBox1.addItem("line" + counter++);
      //  this.jComboBox1.setSelectedIndex(counter);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (counter == 1) {
            return;
        }
        int i = jComboBox1.getSelectedIndex();
        MyCanvas c = (MyCanvas) jPanel2;

        //if (jRadioButton1.isSelected() == true) {
            //c.removeall();
//            for (Shape s : c.shapesList) {
//                c.removeShape(s);
               // System.out.println("x");
           // }
           //c.repaint();
        //} else {
            c.removeShape(c.shapesList.get(i));
           // System.out.println("y");
        //}

        this.jComboBox1.removeItemAt(counter - 2);
        counter--;
        c.repaint();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
             int count = jComboBox1.getItemCount();
             String[] shapesNames = new String[count];
             
             for(int i =0; i<count; i++){
                 shapesNames[i]= jComboBox1.getItemAt(i);
            }
            controller.setShapesNames(shapesNames); 
            controller.save(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
         int i = jComboBox1.getSelectedIndex();
        System.out.println(i);
        MyCanvas c = (MyCanvas) jPanel2;
        Shape s = c.shapesList.get(i);
        try {
            Shape newShape = (Shape) s.clone();// return null
            if (newShape == null) {
                System.out.println("shape is null");
            }
            System.out.println("we're getting position ");
            Point position = newShape.getPosition();
            System.out.println("we got position ");
            position.x += 70;
            position.y += 70;
            newShape.setPosition(position);
            System.out.println("we're adding ");
            c.addShape(newShape);
            this.jComboBox1.addItem(newShape.getClass().getSimpleName() + counter++);
            c.repaint();
        } catch (CloneNotSupportedException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View instance = new View();
                instance.setVisible(true);
                instance.setLocationRelativeTo(null);
                instance.pack();
                instance.setSize(new Dimension(830, 550));
                instance.setcontroller(new PaintControl(instance.getMyCanvas()));
                //.add(new TestPane());
            }
        });
    }
    static int counter = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel2() {
        return jPanel2;
    }

    private MyCanvas getMyCanvas() {
        return (MyCanvas) jPanel2;
    }

    private void setcontroller(PaintControl paintControl) {
        this.controller = paintControl;
    }

}
